# Generated by Django 5.1.3 on 2025-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorChannelData',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('creator_id', models.CharField(max_length=255)),
                ('channel_name', models.CharField(default='temp_channel', max_length=255, unique=True)),
                ('channel_description', models.TextField()),
                ('ban_reason', models.JSONField()),
                ('time_out_reason', models.JSONField()),
            ],
            options={
                'db_table': 'creators_data"."creator_channel_data',
            },
        ),
        migrations.CreateModel(
            name='ChannelInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'creators_data"."channel_invitation',
                'unique_together': {('user_id', 'channel_name')},
            },
        ),
    ]
