# Generated by Django 5.1.3 on 2025-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_reason', models.TextField(blank=True, null=True)),
                ('timed_out_reason', models.TextField(blank=True, null=True)),
                ('timed_out_initial_time', models.DateTimeField(blank=True, null=True)),
                ('is_timed_out_duration_completed', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_banned_or_timedout_reason"."user_moderation',
            },
        ),
    ]
