# Generated by Django 5.1.3 on 2025-04-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0002_usermoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoderation',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
