# Generated by Django 5.1.3 on 2025-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0003_usermoderation_banned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoderation',
            name='banned_reason_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermoderation',
            name='timed_out_reason_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
